### ISSUE TITLE
[Feature Request] Support Response and Request

### ISSUE THREAD

**Issue by Hebilicious** [unjs/h3#401]
### Describe the feature

H3 can be inconvenient to work with in environments that are not Node.js based, such as cloudflare, lagon, vercel-edge etc

- An alternative API to`event.node`, `event.request`  would be more natural to use.
- An way to return a native `Response` from an event handler would be great.

Example :
```ts
defineEventHandler(event => {
console.log(event.request) //... Request object
console.log(event.node) //... undefined
return new Response("Hello world") // Works as intended 
} )
```

Additionally, it should be possible to return a `Response` in node environments as well.

### Additional information

- [X] Would you be willing to help implement this feature?

```[tasklist]
### Tasks
- [ ] #421
- [ ] #436
- [ ] https://github.com/unjs/h3/pull/454
- [ ] https://github.com/unjs/h3/issues/458
```

**Comment by pi0** [comment]
Response support implemented by https://github.com/unjs/h3/pull/436
